language: php

php:
    - 7.2
    - 7.3

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.1.*
    - SYMFONY_VERSION=4.2.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - |
        composer require \
            symfony/asset:${SYMFONY_VERSION} \
            symfony/config:${SYMFONY_VERSION} \
            symfony/console:${SYMFONY_VERSION} \
            symfony/dependency-injection:${SYMFONY_VERSION} \
            symfony/filesystem:${SYMFONY_VERSION} \
            symfony/finder:${SYMFONY_VERSION} \
            symfony/form:${SYMFONY_VERSION} \
            symfony/framework-bundle:${SYMFONY_VERSION} \
            symfony/http-foundation:${SYMFONY_VERSION} \
            symfony/http-kernel:${SYMFONY_VERSION} \
            symfony/options-resolver:${SYMFONY_VERSION} \
            symfony/templating:${SYMFONY_VERSION} \
            symfony/translation:${SYMFONY_VERSION} \
            --no-update --no-scripts
    - |
        composer require \
            symfony/browser-kit:${SYMFONY_VERSION} \
            symfony/security-csrf:${SYMFONY_VERSION} \
            symfony/twig-bundle:${SYMFONY_VERSION} \
            --no-update --no-scripts
    - composer update --prefer-dist

script:
    - composer validate --strict

    - composer analyse

    - vendor/bin/phpspec run
    - vendor/bin/phpunit
